### ISSUE TITLE
Admin UI performance testing & benchmark

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12241]
We have [Admin UI performance improvements #80](https://github.com/wagtail/roadmap/issues/80) on the Wagtail roadmap, which is currently very open-ended. We need to do a benchmark of the Wagtail admin interface so we can plan possible improvements from a more curated backlog – and have a way to better quantify the impact of known issues.

In [RFC 101](https://github.com/wagtail/rfcs/pull/101), we’re proposing to do this benchmark in time for Wagtail 6.3\*, with the improvements scheduled for v6.4\* (February 2025).

## Scope

To be confirmed. Most likely using a tiered approach, where we’d do more manual testing for high-value user flows, automation only elsewhere. See [wagtail-tooling](https://github.com/thibaudcolas/wagtail-tooling) for examples of scripted testing of the admin UI, and [Wagtail | 5.1 UI overview](https://docs.google.com/spreadsheets/d/1FMSA_BI3ZvkeAvuaIL2QtqRTgMNwz_vhfKBeyx2Onnk/edit?gid=1962441802#gid=1962441802) for a recent recording of all admin functionality.

## Methodology

To be confirmed. Most likely:

- A suite of tools to run manual checks with (DevTools runtime Performance panel?)
- Lighthouse to run automated checks across a wider group of views
- TBC tool set up to run ongoing benchmark tests (Lighthouse CI?)

## Reporting

To be confirmed. Possible options:

- Spreadsheet
- GitHub issues with labels
- Github Project board (with issues)

## Related work

In Wagtail:

- [WCAG 2.2 AAA* audit of the Wagtail admin – Nov 2023 #11180](https://github.com/wagtail/wagtail/discussions/11180)
- [RFC 78: Adopt Stimulus](https://github.com/wagtail/rfcs/blob/main/text/078-adopt-stimulus-js.md)
- [CSP compatibility issues #1288](https://github.com/wagtail/wagtail/issues/1288)
- [Remove support for Safari 15 #11257](https://github.com/wagtail/wagtail/issues/11257)

Other projects:

- [django-asv](https://github.com/django/django-asv) – Python benchmarks for Django over time, done with airspeed velocity
- [wagtail-bakerydemo-archive](https://github.com/thibaudcolas/wagtail-bakerydemo-archive) to test past versions of the admin UI.
- [DEP 84: Rejuvenate form media #84](https://github.com/django/deps/pull/84)

## Tasks

- Planning
	- [ ] Discuss one-off audit / tests vs. setup of repeatable benchmarks
	- [ ] Plan the auditing / testing scope
	- [ ] Tooling review
	- [ ] Plan auditing / benchmarking methodology
	- [ ] Plan reporting format
- Testing / benchmarking
	- TBC
- Reporting
	- Collate all identified issues separately from existing open issues
	- Triage / connect with open issues
	- Impact-effort matrix
	- Update [Admin UI performance improvements #80](https://github.com/wagtail/roadmap/issues/80) 

## Working on this

Assigning this provisionally to myself and @laymonage, but we could use support from others. Either to test more parts of the Wagtail admin, or incorporate better methodologies in our testing. Or for the initial planning.

**Comment by thibaudcolas** [comment]
Here are the pages / components we’ve decided to test, though we’re keen to add more if time is available:

| View / Component | Manual testing | Automated testing |
| ---------------- | -------------- | ----------------- |
| Dashboard        | Yes            | Yes               |
| Userbar          | Yes            | Yes               |
| Pages menu       |                | Yes               |
| Pages Edit       | Yes            | Yes               |
| Pages listing     | Yes            | Yes               |
| Images listing   |                | Yes               |
| Snippets listing | Yes            | Yes               |
| Styleguide       | Yes            | Yes               |
