### ISSUE TITLE
Show where comments are on the minimap

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12333]
### Describe the solution you'd like

Part of #10055. We want the minimap to reflect highlights on the form. Currently we show validation errors; it would be nice to also show comment counts for specific fields. Current design:

<img width="458" height="315" alt="Comments indicators" src="https://github.com/user-attachments/assets/c019f04f-6609-4e64-96cb-1bc238f6566e" />

### Working on this

Requires React, Stimulus, JS/TS skills. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### Tasks

- [ ] Display the presence of comments in [MinimapItem](https://github.com/wagtail/wagtail/blob/main/client/src/components/Minimap/MinimapItem.tsx)
- [ ] Add unit tests (/ and Storybook?)
- [ ] Retrieve the number of comments for a given minimap item (@thibaudcolas)
- [ ] Make sure `MinimapItem` renders with its comment indicator when number of comments > 0

**Comment by logicalavi09** [comment]
@thibaudcolas Hi! I'd like to work on this issue. I’ve been exploring the minimap and comment system in Wagtail and can start implementing the comment indicators in MinimapItem. Please let me know if I can proceed.
and one more thing please, do let me know if this issue need any ui/ux engineer involvement.
