### ISSUE TITLE
ES modules dynamic import loading for UI components

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12705]
Follow-up of [Wagtail 6.3 admin UI performance audit](https://github.com/wagtail/wagtail/discussions/12578). We have a lot of opportunities to make Wagtail faster by deferring the loading of some of our UI components. This can be done with ES modules dynamic import (`import()`), and import maps.

Here are specific opportunities identified as part of the audit:

- Axe
- Downshift / ComboBox component
- Pages explorer (React transition group, focus trap)
- Tippy.js
- DialogController

There isn’t necessarily a performance win in doing this for every component, but in some cases it could help. The advantage of deferring loading is other components won’t be competing for JS files downloading / parsing / execution work, but that only applies if the JS code that is deferred is consequential.

---

As part of this work, this would also be a good opportunity to add asynchronous loading attributes to existing `<script>` tags.

## Tasks

- [ ] Update the Webpack configuration to support dynamic imports
- [ ] Create an import map for the Wagtail admin
- [ ] Introduce dynamic import loading setup for one UI component, which we can then roll out elsewhere in the future.

**Comment by hsd2514** [comment]
hey i would like to work on this issue
