### ISSUE TITLE
Remove "wagtail" prefix from all modules

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#1504]
Since we've dropped Django 1.6 support, we can now rename all modules to get rid of their "wagtail" prefix. For example: `wagtail.wagtailcore` => `wagtail.core`

I would like to propose two exceptions to this:
- `wagtail.contrib.wagtailmedusa` => `wagtail.contrib.staticsitegen`
- `wagtail.contrib.wagtaildocs` => `wagtail.documents`

I'd also like to propose we take this opportunity to move some apps to contrib:
- `wagtail.wagtailforms` => `wagtail.contrib.forms`
- `wagtail.wagtailredirects` => `wagtail.contrib.redirects`
- `wagtail.wagtailembeds` => `wagtail.contrib.embeds`

We should start with contrib apps, then move on to core apps.

Progress:
- [ ] `wagtail.contrib.api` #1498 
- [ ] `wagtail.contrib.frontendcache` #1499
- [ ] `wagtail.contrib.staticsitegen` #1500 
- [ ] `wagtail.contrib.routablepage`
- [ ] `wagtail.contrib.sitemaps` #1503
- [ ] `wagtail.contrib.styleguide` #1585
- [ ] `wagtail.contrib.forms`
- [ ] `wagtail.contrib.redirects`
- [ ] `wagtail.contrib.embeds`
- [ ] `wagtail.admin`
- [ ] `wagtail.core`
- [ ] `wagtail.documents`
- [ ] `wagtail.images`
- [ ] `wagtail.search`
- [ ] `wagtail.sites`
- [ ] `wagtail.snippets`
- [ ] `wagtail.users`

**Comment by kaedroho** [comment]
@gasman said in last weeks dev meeting that we should take the following approach:

 - Rename each module removing the "wagtail" prefix
 - Add alias modules with the old names that import from the new locations (so code continues to work)
 - Do not add deprecation code yet, the old locations will still be the primary places to import from (relying on the alias modules to forward the imports through to actual locations)
 - When all modules are renamed, switch to using the new module names in one go and add deprecation warnings to the alias modules
 - After two release cycles, remove the alias modules

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Completed in #3918
