### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#3917]
Top-level issue to track progress towards supporting Django 2.0 in Wagtail 2.0 - further tickets may be opened and linked here to track sub-tasks.

Plan (items under the same heading can be done in parallel):

## Old version removal

- [x] Remove Django 1.8, Django 1.10 and Python 2.7 from CI
- [x] Ensure that the demo projects we intend to develop against (bakerydemo, and wagtaildemo if we haven't yet switched vagrant-wagtail-develop to bakerydemo) are running against Python 3 and Django 1.11

## Cleanup

- [x] Seek out and destroy all fallback code handling:
  - [x] Django 1.8 / 1.10 (#3924, #3932)
  - [x] Python 2.7 (#3934)
- [x] Fix all deprecation warnings in test suite when running against Django 1.11 (NB may overlap with the above: some warnings can't effectively be fixed while <1.11 compatibility code remains in place)
- [ ] Optional: Replace use of django.utils.six with Python3-specific equivalent code
- [ ] Optional: Eliminate use of `django.utils.deprecation.MiddlewareMixin` ([docs](https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware))

## Upgrade

- [x] Check release notes at https://docs.djangoproject.com/en/dev/releases/2.0/ and make any necessary changes
- [x] Run tests against the latest pre-release of Django 2.0 and fix anything that breaks (#4085)

## Finalisation

- [x] Update dependencies in setup.py (#4085)
- [x] Add Django 2.0 to CI (#4085)
- [x] Update setup.py and tox/travis config to reference Django 2.0-compatible releases of django-modelcluster, django-treebeard and django-taggit, when available

Since this is likely to be a large and disruptive change to the codebase, we should aim to keep individual PRs as small and focused as possible, and review them promptly.

**Comment by kaedroho** [comment]
Django have also dropped support for Python 3.4: https://github.com/django/django/commit/cfff2af02be40106d4759cc6f8bfa476ce82421c

**Comment by FlipperPA** [comment]
I believe Python 3.4 support isn't being dropped until Django 2.1. There was a fairly big discussion on it here:

https://groups.google.com/forum/#!searchin/django-developers/python$203.4%7Csort:date/django-developers/4rbVKJYm8DI/1LkPWDcYBQAJ

And the associated PR after the discussion: https://github.com/django/django/pull/8884

**Comment by kaedroho** [comment]
Ahh yes, that's right. They dropped support two weeks ago from master, but they've already branched off ``stable/2.x``. Ignore my previous comment!

**Comment by gasman** [comment]
Completed in cca76538397b553a6ac9a66637a8e28dc8bb45f7
