### ISSUE TITLE
Make rich text soft line breaks configurable with rich text features

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#4445]
Feature request.

### Issue Summary

The rich text features used to turn on/off heading levels, list items, etc should also make it possible to toggle soft line breaks (`\n` in the editor converted to `<br>` in the HTML output). At the moment line breaks are turned on and there is no way to disable them.

See https://github.com/wagtail/wagtail/issues/4266#issuecomment-364750160 and https://github.com/wagtail/wagtail/pull/4268#issuecomment-365994579 for more context.

The current line break definition is here:

https://github.com/wagtail/wagtail/blob/7841f54fe873d128d21a30cb19752c7081ec7b1a/client/src/components/Draftail/index.js#L90-L93

**Comment by yanndinendal** [comment]
It could also be useful to have an `InlineRichTextField` which would allow editors to add bold, italic and links but prevent them adding line breaks (`br`), or other blocks like like `ul`, `ol`, ...  
And especially **not** wrap the output in a `<p>` tag.

**Comment by zerolab** [comment]
I can see how `InlineRichTextField` would relate to https://github.com/wagtail/rfcs/pull/60

**Comment by thibaudcolas** [comment]
I believe this would be [RFC 46](https://github.com/wagtail/rfcs/pull/46). I’ve made a draft attempt at implementing this (https://github.com/wagtail/wagtail/pull/7249), it worked well, just didn’t have the time to finish it.

**Comment by thibaudcolas** [comment]
Just adding notes to this specific to the page editor 2022 project:

### Tasks

- [ ] Review WIP implementation
- [ ] Decide on breaking change / no breaking change
- [ ] Rebase, tweak, merge

### Acceptance criteria

- [ ] As a developer, I can configure whether a given rich text field has soft line breaks available or not.

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @jacobtoppm or @gasman

**Comment by david-smejkal** [comment]
I've tried adding a custom "soft" line break feature to Draftail but unfortunately I couldn't quite get it to behave properly.
I couldn't figure out how to render those line breaks in the admin area after they are saved. Specifically when it loads them from the database and renders them in the the rich text area in Wagtail's backend.

![wagtail-draftail-custom-linebreak-feature-presistency-issue](https://raw.githubusercontent.com/david-smejkal/assets/b5a0ac0927cf6528321208efd7e6a6980185a18d/issues/wagtail-draftail-custom-linebreak-feature-persistency-issue.gif)

```python
from wagtail import hooks
from wagtail.admin.rich_text.converters.html_to_contentstate import LineBreakHandler

@hooks.register('register_rich_text_features')
def register_br_feature(features):
    """
    Feature that injects <br> tags in rich text area. Unfortunately currently it doesn't render the <br> tag
    properly in the backend. The built-in line break handling or something else is overwriting it.
    This means that subsequent saves of rich text areas will remove any previously stored line breaks.
    TODO: Fix it
    """
    feature_name = 'br'
    type_ = 'br'
    tag = 'br'
    control = {
        'type': type_,
        'label': '↵',
        'description': 'Line break',
        # 'element': 'br', # This breaks react rich text rendering in the backend, TODO: Fix it
    }
    features.register_editor_plugin(
        'draftail', feature_name, draftail_features.BlockFeature(control)
    )
    db_conversion = {
        'from_database_format': {
            tag: LineBreakHandler(), # This is currently doing nothing, TODO: Fix it
        },
        'to_database_format': {
            'block_map': {type_: {"element": 'br'}},
        },
    }
    features.register_converter_rule('contentstate', feature_name, db_conversion)
    features.default_features.append('br')
```

Any idea how to fix this issue?

**Comment by thibaudcolas** [comment]
See first attempt to implement this in #5149. After 5 years, this PR looks like it won’t go further, but would make a good base for someone else to take this on. Specific changes needed:

- Add a deprecation warning for fields without `br` enabled
- Automatically turn on the `br` feature for fields that contain `br` already

```
RemovedInWagtail70Warning: The BlogPage.body RichTextField [or RichTextBlock] does not have the
`br` feature enabled. In Wagtail 7.0 this will prevent inserting line breaks. To silence this
warning, set WAGTAIL_RICH_TEXT_ALLOW_NO_BR = True
```
