### ISSUE TITLE
Tracking issue for search autocomplete API (RFC 27)

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4937]
This issue is to track progress on implementing the new autocomplete API in Wagtail.

Phase 1: Groundwork:

- [x] Implement AutocompleteField
- [x] Implement .autocomplete() method on search backends and BackendAutocompleteQueryCompiler class

Phase 2: Elasticsearch:

- [x] Implement indexing support for AutocompleteField
- [x] Implement ElasticsearchAutocompleteQueryCompiler

Phase 2: PostgreSQL search:

 - [ ] Implement indexing support for AutocompleteField
 - [x] Implement PostgresAutocompleteQueryCompiler

Phase 3: Launch

 - [ ] Document autocomplete API
 - [ ] Deprecate partial_match
 - [ ] Advertise new API in release notes

**Comment by BertrandBordage** [comment]
@kaedroho I see you assigned me. Was it for “Implement indexing support for AutocompleteField”? It’s already done and merged :slightly_smiling_face: (checked the list item)

**Comment by kaedroho** [comment]
Oh, I couldn't find any mention of it in the code. Thanks!

**Comment by kaedroho** [comment]
@BertrandBordage Are you sure about that? I'm looking at the indexing code and can't see it: https://github.com/wagtail/wagtail/blob/master/wagtail/contrib/postgres_search/backend.py#L94-L96

**Comment by BertrandBordage** [comment]
Aaaaah, sorry, you’re right. Brain fart.

**Comment by kaedroho** [comment]
PR for finishing PostgreSQL implementation: https://github.com/wagtail/wagtail/pull/5960

**Comment by kaedroho** [comment]
Rest of the implementation of this is in now. Just docs and deprecation left to do!

**Comment by lb-** [comment]
@kaedroho  not sure if we wanted to be louder about this but I have added 02d6d27a9c687c8d5e24ddba6d59b98a96e4d04d to the release notes.

Feel free to update if you think that is not sufficient

**Comment by maqnius** [comment]
Hey everyone,

I was thinking where to put this and I guessed, that it would be easiest if I just comment here - even though this thread is a little old, but I am not sure if this is worth an own issue. 

Getting to the point:

I was wondering why it seems that there is no work intended to support the autocomplete search using the Wagtail Rest Api. For example by extending the `PagesAPIViewSet` or something like this. 

Is in planned somehow somewhere and I just didn't find it?

Thank you so much :)

**Comment by thibaudcolas** [comment]
I see the last un-checked item here was _Deprecate partial_match (following the [Deprecation Path](https://github.com/wagtail/rfcs/blob/master/text/027-autocomplete.md#deprecation-path))_. This is done as of [Wagtail 6.0 removals](https://docs.wagtail.org/en/stable/releases/6.0.html#other-removals), so I’ll close this issue now.
