### ISSUE TITLE
Make sure all actions in the CMS have a textual label relevant to screen readers

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#5274]
From https://github.com/wagtail/wagtail/issues/4199#issuecomment-358640129,

> Some actions on the admin are available as icon-only links, such as the ordering actions found in the table headers. In this case, the screen reader doesn't speak the name (label) of that link, so the user would not be able to identify what the link does.

<details>

<summary>Approaches</summary>

Approaches to resolve this issue might include:

- Use Bootstrap's "**sr-only**" class to add a hidden textual description. For instance, instead of:

```
<a href="/admin/sites/?ordering=name" class="icon icon-arrow-down-after"></a>
```

It could be:

```
<a href="/admin/sites/?ordering=name" class="icon icon-arrow-down-after"><span class="sr-only">Order by name</span></a>
```

- Use the **aria-label** attribute on the element to add a textual alternative to the icon. For example:

```
<a href="/admin/sites/?ordering=name" class="icon icon-arrow-down-after" aria-label="Order by name"></a>
```

</details>

Additional readings on the importance of textual alternatives:

- [The Visual-only icon problem](https://www.joedolson.com/2014/06/visual-icon-problem/)

---

Solutions to this include:

- Adding labels where there is none, either visible so sighted users understand the action better like in #5187, or for screen readers only
- Making sure existing screen-reader-only labels provide enough context for users to understand the action

Here are parts of the UI I found where this would most likely be a problem:

* Table headings sort
* Dashboard “metrics” icons
* “Public”/”Private” page privacy toggle
* Modals’ “Close” button
* “>” explore caret in Pages menu, and pages listing
* “\+” add child pages in pages listing
* “Account settings” submenu (caret)
* Datepicker widget

**Comment by thibaudcolas** [comment]
Here are the recommendations from @Katielocke3 on parts of the UI that need to be changed:

- Table headings 'sort' action voice over changed to announce ‘Link, Sort child pages by ‘Title’
- Dashboard “metrics” icons to provide more content by announcing ‘Link, 2 Documents created in ‘CMS name’
- Public/privacy toggle action to provide more context by announcing 'Link, privacy, selected Public
- Edit lock toggle action to provide more context by announcing 'Link, edit lock, selected UNLOCKED
- Status toggle action to provide more context by announcing 'Link, status, selected LIVE
- Modals’ “Close” button icon to provide more content by announcing 'Pop up modal, close, button.
- 'Add child pages' icon button to pronounce the word 'Add' rather than 'A-D-D
- Add child page button to listing page Icon to voice over announcement: ‘Link, Add child page to <listing name>
- Improve add child page icon to a darker colour on focus state (10% darker teal)
- Clarify that the user is focused on the side navigation by improving the voice-over command to say ‘Navigation’, for example: ‘link, Settings list navigation, 9 items

**Comment by helenb** [comment]
I have discussed the change to the public / private privacy buttons with Katie, and agreed on the following text which is a bit clearer:

“Set page privacy. Current status: Private”

And for users who don’t have the ability to set the page privacy

“Page privacy. Current status: Private”

**Comment by helenb** [comment]
Further text changes from the original spec above noted here (discussed with Katie)

**Page status**
If the page is live, there is a link to the live page, otherwise there is no link.

So the text will be either
Current page status: Live. Visit the live page.
or:
Current page status: Draft

**Editor lock**
The lock switch is a button that displays the current status and either locks or unlocks the editor lock.

The text will be set to either:
Remove editor lock. Current status: Locked
or:
Apply editor lock. Current status: Unlocked

**Comment by helenb** [comment]
One further change from the above: there is an issue where Voiceover on Safari is not reading text in the correct order when it is in the following format

```
<span class="visuallyhidden">{% trans "Current page status:" %}</span>
<span class="">{{ page.status_string }}</span>
<span class="visuallyhidden">{% trans "Visit the live page:" %}</span>
```

So instead I have moved 'Visit the live page' to a title tag on the link.

**Comment by thibaudcolas** [comment]
Here is a recap of what’s where since this covers multiple changes that are split between PRs:

- [ ] #5372 Table headings 'sort' action
- [ ] #5372 Dashboard “metrics” icons
- [ ] #5372 Public/privacy toggle action
- [ ] #5372 Edit lock toggle action
- [ ] #5372 Status toggle action
- [x] #5377 Modals’ “Close” button
- [ ] #5380 'Add child pages' icon button
- [ ] #5380 Add child page button to listing page
- [ ] #5382 Improve add child page icon to a darker colour on focus
- [ ] TODO Clarify that the user is focused on the side navigation by improving the voice-over command to say ‘Navigation’, for example: ‘link, Settings list navigation, 9 items

**Comment by thibaudcolas** [comment]
Moving "Clarify that the user is focused on the side navigation by improving the voice-over command to say ‘Navigation’, for example: ‘link, Settings list navigation, 9 items" to #5337 – we need to do other changes to the main menu as part of this, it would make sense to cover label / context changes at the same time.

**Comment by thibaudcolas** [comment]
Addressed in #5372.
