### ISSUE TITLE
Phase out icon font and use SVG everywhere

### ISSUE THREAD

**Issue by allcaps** [wagtail/wagtail#6107]
In https://github.com/wagtail/wagtail/pull/4821 the menu font icons are replaced with SVG icons. It is a nice start. In this issue an overview of work to be done to have SVG icons everywhere.

We choose to switch to SVG icons for accessibility (title attr and aria labels). But SVG icons are also easier to maintain, customise and extend. All icons are all-ready converted to SVG. We need to dorp the icon font reference (CSS) and use the SVG icon like this:

    {% load wagtailadmin_tags %}
    {% icon name="rocket" classname="..." title="Launch" %}

The intention is to drop Wagtail font icon and CSS from future Wagtail releases. We need to decide what is needed for a proper deprecation process.

I'd propose to keep this issue as a meta issue to keep track of progress. Work can be done in separate issues and pull requests. To keep pull requests reviewable.

## Priority

 - [x] Images in rich text have oversized image icon (SVG regression) #6142
 - [x] Menu icon positioning https://github.com/wagtail/wagtail/issues/6297 Will be solved by switching to SVG.

## Icon font usage that needs to be refactored

- [x] Header icons ``<h1 class="icon icon-image">Images</h1>`` https://github.com/wagtail/wagtail/pull/6121
- [x] Messages framework messages ``messages success`` https://github.com/wagtail/wagtail/pull/6124
- [x] Button plus ``button bicolor icon icon-plus`` #6151
- [x] Dropdown buttons ``dropdown-toggle icon icon-arrow-down``  #6151 
- [x] More buttons ``o-icon  c-dropdown__toggle  [ icon icon-arrow-down``  #6151 
- [x] Wagtail user bar and menu items `wagtail-icon wagtail-icon-wagtail` https://github.com/wagtail/wagtail/pull/6125
- [x] `MenuItem`s (including `ModelAdminMenuItem` and `GroupMenuItem`) #6402 
- [x] Help text ``help-block help-critical`` @Scotchester #6457 
- [x] Breadcrumb (home icon) #6438 @allcaps
- [x] Pagination, previous and next chevrons @Scotchester #6573
- [x] SearchAreas API @thibaudcolas #6493
- [x] Settings menu item @thibaudcolas #6649
- [x] All choosers ``.page-chooser .unchosen:before`` @Stormheg 
- [x] StreamField buttons #7565
- [x] Spinner @stevedya 
- [x] [Error messages (cross)](https://github.com/wagtail/wagtail/blob/main/client/scss/components/forms/_error-message.scss)
- [x] [ModelAdmin ButtonHelper](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/modeladmin/helpers/button.py#L6-L9)
  - Implementation idea: Add icon property to ButtonHelper that, if present, will output the SVG in the [ModelAdmin button template](https://github.com/wagtail/wagtail/blob/bcc7df10d63da92b9051e2096246cb9bd8ab5336/wagtail/contrib/modeladmin/templates/modeladmin/includes/button.html).
- [x] [ModelAdmin PageChoiceField hierarchy arrows](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/modeladmin/forms.py#L8-L15)
  - Implementation idea: Replace hard-coded icon font `span` with imported SVG icon.
- [x] [page_listing_buttons, Add child page](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/wagtail_hooks.py#L247-L250)
  - Implementation idea: Looks like this will require adding an icon property to [the Button widget](https://github.com/wagtail/wagtail/blob/70364972409e962b5d5f8b30537b2b81fb3e2a30/wagtail/admin/widgets/button.py#L29) that, if present, will output the SVG in the rendered HTML.
- Listings’ up and down ordering arrows
    - [x] [wagtailadmin_tags.py#L419](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templatetags/wagtailadmin_tags.py#L419)
    - [x] [documents/list.html](https://github.com/wagtail/wagtail/blob/main/wagtail/documents/templates/wagtaildocs/documents/list.html)
    - [x] [wagtailsearchpromotions/list.html](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/search_promotions/templates/wagtailsearchpromotions/list.html)
    - [x] [wagtailredirects/list.html](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/redirects/templates/wagtailredirects/list.html)
    - [x] [tables/column_header.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/tables/column_header.html)
    - [x] [users/list.html](https://github.com/wagtail/wagtail/blob/main/wagtail/users/templates/wagtailusers/users/list.html)
    - [x] [includes/result_list.html](https://github.com/wagtail/wagtail/blob/main/wagtail/contrib/modeladmin/templates/modeladmin/includes/result_list.html)
- [x] Login page user and password field icons
- [x] add_subpage.html Add subpage icons
- [x] history.html Edit this page link icon
- [x] Page reordering `icon-grip` for drag indicator
- Page listings "Explore subpage" icons
    - [x] _navigation_choose.html 
    - [x] _navigation_explore.html 
    - [x] _navigation_move.html
- [x] _page_title_explore.html Sites menu icon
- [x] workflows/index.html add
- [x] workflows/select_task_type.html add
- [x] workflows/task_index.html add
- [x] workflows/includes/workflow_pages_formset.html add
- [x] workflows/task_chooser/includes/select_task_type.html add
- [x] modeladmin/inspect.html Back button @vossisboss
- [x] wagtailredirects/index.html Header icon
- [x] documents/_file_field.html, images/_file_field.html source document/image link icons
- [x] wagtailimages/multiple/add.html add
- [x] wagtailusers/users/create.html "Go to next tab"

### Will be fixed as part of slim sidebar rework

- [x] Hamburger menu @allcaps Should this be a button? Currently a div.
- [x] Search submit button @allcaps
- [x] Main nav `#footer. arrow down, account, logout`
- [x] Main nav menuitem, sub-menu item

### Will be fixed as part of the page editor 2022 project

- [x] [Inputs](https://github.com/wagtail/wagtail/blob/main/client/scss/components/_forms.scss) ``.url_field .input:before``
- [x] Datetimepicker icons https://github.com/wagtail/wagtail/blob/main/client/scss/overrides/_vendor.datetimepicker.scss
- [x] edit panels `.title-wrapper:before` Fish finger icons https://github.com/wagtail/wagtail/blob/main/wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
- [x] Preview button icon
- [x] Privacy switch button icons
- [x] Privacy switch panel icons
- [x] _locked_indicator.html locked icon
- [x] Dropdown button down arrow (_button_with_dropdown.html, locale_selector.html)

### Additional icon font work

- [x] Add utility CSS to make sizing and positioning easy for third party and custom works. https://github.com/wagtail/wagtail/issues/6142#issuecomment-643596671 -- #6189
- [x] Sprite view + IE11 support, and cache ~~https://github.com/wagtail/wagtail/pull/6231~~ https://github.com/wagtail/wagtail/pull/6243
- [x] Fix icon size in style guide #6189
- [x] `class_name` or `classname`. https://github.com/wagtail/wagtail/pull/6125#discussion_r439176243
- [x] Update [wagtailfontawesome](https://gitlab.com/alexgleason/wagtailfontawesome) to use SVG OR provide a new drop-in replacement package. 
I created a replacement package https://pypi.org/project/wagtail-font-awesome-svg/0.0.2/

## Code cleanup

- [x] Remove unused code https://github.com/wagtail/wagtail/blob/main/client/scss/components/_chooser.scss#L36-L39

## Documentation

- [x] Add documentation https://github.com/wagtail/wagtail/pull/6028
- [x] Update the documentation on icon usage https://docs.wagtail.org/en/latest/advanced_topics/icons.html

## Deprecation process

- [x] Remove wagtail icon font (we need it for backward compatibility. So deprecate and remove at major release).
- [x] Remove any FontAwesome specific workaround (`fa-`).
- [x] Remove choosers styles referring to `icon-font`.
- [x] Remove mixin https://github.com/wagtail/wagtail/blob/main/client/scss/tools/_mixins.general.scss#L88
- [x] Remove variables https://github.com/wagtail/wagtail/blob/main/client/scss/settings/_variables.scss#L131
- [x] Remove styles set on `::before` pseudo elements for icon fonts only.
- [x] Remove all styles referring to "iconfont"
- [x] Update test cases to consistently use SVG icon references (check for `#icon-foo` rather than `icon-foo`).

**Comment by lb-** [comment]
Wagtail userbar - wagtail/admin/templates/wagtailadmin/userbar/base.html
uses
`<i class="wagtail-icon wagtail-icon-wagtail"></i>`

**Comment by zerolab** [comment]
Working on buttons with icons

**Comment by thibaudcolas** [comment]
@Scotchester @rinti and I have expressed some interest in trying to get the bulk of this done in time for Wagtail 2.11, scheduled for release on 2020-11-01. With the 2-week release candidate period, that leaves us until 2020-10-16 to tackle all of the icons changes, and the new documentation.

I’ve tagged us on the individual tasks we’re intending to do – if others want to pick up other tasks please let people know via a comment.

@allcaps how does that sound?

**Comment by thibaudcolas** [comment]
Heads’up for people working on this – we’re going to be reworking icons used in the page editor as part of #7739. I believe this includes all 3 items still unticked from the list above (edit panels, URL inputs, spinner).

**Comment by thibaudcolas** [comment]
I have just updated the list of what’s remaining based on a the work in #8054.

**Comment by thibaudcolas** [comment]
Now updated based on the implementation of page editor form styles in #8921.

**Comment by lb-** [comment]
Privacy indicator icon & locked indicator icon will be updated to use the new SVG icons via https://github.com/wagtail/wagtail/pull/8954

`wagtail/admin/templates/wagtailadmin/pages/listing/_privacy_indicator.html`
`wagtail/admin/templates/wagtailadmin/pages/listing/_locked_indicator.html`

Note: these are shown in page listings such as locked pages reports or dashboard listings.

**Comment by NPDebs** [comment]
Hi 👋🏼 
I'm an Outreachy intern and I would love to work on this issue if it is still open for contribution. Thank you

**Comment by thibaudcolas** [comment]
Hi @NPDebs! There’s lots in here that can be picked up, though the tasks on this list are pretty advanced.

There are two tasks that we haven’t discussed and I think would make excellent additions for a newcomer to take on, if you’re keen:

1. Make it possible for us to preserve the `xmlns` attribute in our SVG files, but remove it when we process the files in Python.
2. Make it possible for us to preserve HTML comments in our SVG files, but remove them when we process the files in Python.

## For the xmlns attribute

Take this file for example:

https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/icons/ellipsis-v.svg

If we changed the first line to:

```xml
<svg xmlns="http://www.w3.org/2000/svg" id="icon-ellipsis-v" viewBox="0 0 192 512">
```

Then the file would be valid and previewable in lots of systems (Mac, Windows, GitHub).

The problem is we only want the attribute to be there in the stored file, but it needs to be removed when we load it in Wagtail in a browser. We’d need to change this code: https://github.com/wagtail/wagtail/blob/09a225730aedc7298902979a0a4bf210a03969fe/wagtail/admin/views/home.py#L300

I think we’d need to change this line to:

```python
        for icon in all_icons:
            combined_icon_markup += render_to_string(icon).replace("svg", "symbol").replace('xmlns="http://www.w3.org/2000/svg"', "")
```

And then add `xmlns="http://www.w3.org/2000/svg"` to all our existing files. And that should be it?


## For comments

The same file https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/icons/ellipsis-v.svg, has a comment pointing out it comes from FontAwesome. I think those comments are very important for us to keep track of where icons come from, but they again shouldn’t be there when we load the file in the browser.

So again, we’d want to change the same code to find all such lines with comments, and remove them as part of loading the icons.

**Comment by thibaudcolas** [comment]
Tagging as Outreachy task now – @NPDebs please let us know whether you intend to take this on or would prefer to leave it to others.

**Comment by NPDebs** [comment]
> Tagging as Outreachy task now – @NPDebs please let us know whether you intend to take this on or would prefer to leave it to others.

Hi @thibaudcolas 👋🏼
This seems pretty straightforward and beginner-friendly.

However, while waiting for a response, I got assigned to many issues from other organisations. I wouldn't want to delay the completion of this issue.

Please let someone else, e.g @vicky1312 have it. Thanks! 🙌🏼🚀

**Comment by thibaudcolas** [comment]
👍 thanks for letting us know! @vicky1312 go for it if you’re still interested – either of the tasks in https://github.com/wagtail/wagtail/issues/6107#issuecomment-1276245262

**Comment by vicky1312** [comment]
Alright @thibaudcolas I’ll work on it.

**Comment by vicky1312** [comment]
@thibaudcolas I would love to take this, but I need clarification on it. I saw some solutions online, and I want to confirm from you first before taking this up.

For svg icon files with comments, am I to add these lines of code?
<xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:System="clr-namespace:System;assembly=mscorlib"/> in the tag? or is there another solution that would be much preferable?

**Comment by thibaudcolas** [comment]
@vicky1312 for this task I don’t think we need to make any changes to the SVG files. The comments are already in there, see for example [ellipsis-v.svg](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/icons/ellipsis-v.svg). The only changes needed should be in the Python code, so we remove those existing comments.

**Comment by lb-** [comment]
Now that https://github.com/wagtail/wagtail/pull/8886 is merged, I would like to prepare a pull request that updates the icon classname usage from `class_name` to `classname`. See docs - https://docs.wagtail.org/en/latest/contributing/general_guidelines.html#use-classname-in-python-html-template-tag-variables

**I will try to get this PR up soon but wanted to post here unless there are critical objections to this approach.**

I propose that we include backwards compatibility of `class_name` (both can be used) up until 5.0 (even though icons are not official yet, they are pretty much a core API and commonly used by other projects).


Interestingly the top of this issue's description contains the example using the `classname` kwarg not `class_name`.

Example of current usage
https://github.com/wagtail/wagtail/blob/d2167ed705e9bb5c74ba84e027e00935cb833d58/wagtail/admin/templates/wagtailadmin/base.html#L16-L26


Files
* https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/shared/icon.html
* https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templatetags/wagtailadmin_tags.py#L671


### Proposed approach

* Support `class_name` but only when passed in, otherwise it will use the preferred `classname`
* We could also

```python
@register.inclusion_tag("wagtailadmin/shared/icon.html", takes_context=False)
def icon(name=None, classname="icon", title=None, wrapped=False, class_name=None):
    """
    Abstracts away the actual icon implementation.

    Usage:
        {% load wagtailadmin_tags %}
        ...
        {% icon name="cogs" classname="icon--red" title="Settings" %}

    :param name: the icon name/id, required (string)
    :param classname: default 'icon' (string)
    :param title: accessible label intended for screen readers (string)
    :return: Rendered template snippet (string)
    """
    if not name:
        raise ValueError("You must supply an icon name")

    if class_name:
        # just importing here for example - will move to actual imports if doing this
        from wagtail.utils.deprecation import RemovedInWagtail50Warning
        warn(
            "Icon template tag `class_name` has been renamed to `classname`, please adopt the new usage instead.",
            category=RemovedInWagtail50Warning,
            stacklevel=3,# ?? unused on this one
        )

    return {"name": name, "classname": class_name or classname, "title": title, "wrapped": wrapped}
```

**Comment by lb-** [comment]
PR up that implements the approach in the above comment - https://github.com/wagtail/wagtail/issues/6107#issuecomment-1325635281

* https://github.com/wagtail/wagtail/pull/9769 - minimal change to ensure the template tag can support both approaches
* https://github.com/wagtail/wagtail/pull/9770 - to complete the work, updating all usage to use `classname` and also adding deprecation warnings / upgrade considerations

**Comment by thibaudcolas** [comment]
For anyone interested in this, I’m looking for guidance again in #7511. As far as I can tell all remaining font icon usage in Wagtail can be converted to SVG icons, with the exception of the 5 used in the jQuery Datetimepicker (which we want to remove anyway, see #8056).

Here is a regex to help look for (font) icon usage:

```
^(?!.*<(svg|use)).*[^#.](icon-angle-double-left|icon-angle-double-right|icon-arrow-down|icon-arrow-down-big|icon-arrow-left|icon-arrow-right|icon-arrow-right-full|icon-arrow-up|icon-arrow-up-big|icon-arrows-up-down|icon-bars|icon-bin|icon-bold|icon-breadcrumb-expand|icon-calendar|icon-calendar-alt|icon-calendar-check|icon-chain-broken|icon-check|icon-chevron-down|icon-circle-check|icon-circle-plus|icon-circle-xmark|icon-clipboard-list|icon-code|icon-cog|icon-cogs|icon-collapse-down|icon-collapse-up|icon-comment|icon-comment-add|icon-comment-add-reversed|icon-copy|icon-cross|icon-crosshairs|icon-cut|icon-date|icon-desktop|icon-doc-empty|icon-doc-empty-inverse|icon-doc-full|icon-doc-full-inverse|icon-dots-horizontal|icon-dots-vertical|icon-download|icon-download-alt|icon-draft|icon-duplicate|icon-edit|icon-ellipsis-v|icon-error|icon-expand-right|icon-folder|icon-folder-inverse|icon-folder-open-1|icon-folder-open-inverse|icon-form|icon-globe|icon-grip|icon-group|icon-h1|icon-h2|icon-h3|icon-h4|icon-h5|icon-h6|icon-help|icon-history|icon-home|icon-horizontalrule|icon-image|icon-info-circle|icon-italic|icon-key|icon-link|icon-link-external|icon-list-ol|icon-list-ul|icon-lock|icon-lock-open|icon-login|icon-logout|icon-mail|icon-media|icon-minus|icon-mobile-alt|icon-no-view|icon-openquote|icon-order|icon-order-down|icon-order-up|icon-password|icon-pick|icon-pilcrow|icon-placeholder|icon-plus|icon-plus-inverse|icon-radio-empty|icon-radio-full|icon-redirect|icon-repeat|icon-reset|icon-resubmit|icon-rotate|icon-search|icon-site|icon-snippet|icon-spinner|icon-strikethrough|icon-subscript|icon-success|icon-suitcase|icon-superscript|icon-table|icon-tablet-alt|icon-tag|icon-tasks|icon-thumbtack|icon-thumbtack-crossed|icon-tick|icon-tick-inverse|icon-time|icon-title|icon-undo|icon-uni52|icon-upload|icon-user|icon-utensils|icon-view|icon-wagtail-icon|icon-wagtail-inverse|icon-warning)
```

With this, we find the following font icon references in JS/Python/HTML code that _should_ all be convertible to SVG icons with enough effort:

```
arrow-down
arrow-down-after
arrow-right
arrow-right-after
arrow-up
arrow-up-after
doc-full-inverse
edit
grip
image
no-view
plus
plus-inverse
site
view
```

And there are two "text icons" that I believe we will want to preserve as-is:

- `icon-help ?`
- Form submissions listings ordering `▲ ▼`

**Comment by thibaudcolas** [comment]
Just a quick update to say I’ve completed all conversions to SVG icons (PR TBD, contains other work). I’ll close this issue once this gets merged, and create a separate one for cleanup after the usual two-release deprecation process.

There is one chance I’d like us to consider if given the chance: define SVG icon names based on the file names, rather than an `id` attribute. This would make icon definitions even simpler – no need to manually edit the SVG at all if it has been exported appropriately from design tools / icon sets.

**Comment by thibaudcolas** [comment]
This is now complete as far as getting all parts of Wagtail to use SVG for icons. I’ve updated the "Deprecation process" section at the top with tasks to do in Wagtail 6.0 to finally remove all traces of the icon font.

If anyone wants to further help with this – I could use feedback on the release notes for this. They’re currently divided between:

- A "headline feature" section, [Customisable SVG icons](https://docs.wagtail.org/en/latest/releases/5.0.html#customisable-svg-icons)
- Upgrade consideration notes for the [deprecated icon font](https://docs.wagtail.org/en/latest/releases/5.0.html#deprecated-icon-font)
- And related but technically part of #2349 – a list of [deprecated icons](https://docs.wagtail.org/en/latest/releases/5.0.html#deprecated-icons)

And I’ve opened a few issues related issues on `wagtail-font-awesome-svg`, which I’m hoping I will be able to pick up at least some of in time for the 5.0 release but don’t know for sure yet:

- https://github.com/wagtail-nest/wagtail-font-awesome-svg/issues/9
- https://github.com/wagtail-nest/wagtail-font-awesome-svg/issues/10

**Comment by thibaudcolas** [comment]
Thank you @gasman for offering to help with this 😌 here are the last few steps we can now take on as part of Wagtail 6.0.

Things that seem quite clear:

- [ ] Remove wagtail icon font files (we need it for backward compatibility. So deprecate and remove at major release).
- [ ] Remove any FontAwesome specific workaround (`fa-`).
- [ ] Remove Sass `icon()` mixin
- [ ] Remove Sass variables (`$font-wagtail-icons`, the whole of `_variables.icons.scss`)
- [ ] Remove all styles referring to "iconfont"

Things that seem somewhat clear:

- [ ] Remove styles set on `::before` pseudo elements for icon fonts only.

Things that seem unclear:

- [ ] Remove choosers styles referring to `icon-font`.
- [ ] Update test cases to consistently use SVG icon references (check for `#icon-foo` id rather than `icon-foo` class).

**Comment by thibaudcolas** [comment]
w00t! With #11209 completed, this is now _Done_! I’ve also removed our "Adding new icons" page, and kept [a copy as a gist](https://gist.github.com/thibaudcolas/62ebe16cfbeea905472e76d5f7ee5082) in case we ever need it back easily.

Well, that was quite the ride! Thank you @allcaps, @Scotchester, @gasman, @Stormheg, @stevedya, and everyone else who worked on this. I’m elated that as a group we can make big changes like this happen. It’s not always as fast as we might wish, but we take good care of backwards compatibility, and we get things DONE! 🙌

**Comment by lb-** [comment]
Well done everyone!
