### ISSUE TITLE
[RFC 54] Tracking issue for internationalisation implementation

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#6378]
https://github.com/wagtail/rfcs/pull/54

This issue tracks progress on the implementation of RFC 54. As this is a big feature, it's broken down into multiple parts that will be released across 2.11 (November 2020) and 2.12 (February 2021).

### Planned for 2.11

 - [x] Routing bug fix https://github.com/wagtail/wagtail/pull/6426
 - [x] Models https://github.com/wagtail/wagtail/pull/6220
 - Documentation
   - [x] Core models documentation https://github.com/wagtail/wagtail/pull/6377
   - [x] Topic documentation https://github.com/wagtail/wagtail/pull/6436
   - [x] Documentation for API changes https://github.com/wagtail/wagtail/pull/6452
 - [x] Locale management UI https://github.com/wagtail/wagtail/pull/6245
 - [x] Make `Page.copy_for_translation(copy_parents=True)` create missing parents as aliases - https://github.com/wagtail/wagtail/pull/6376
 - [x] API changes  https://github.com/wagtail/wagtail/pull/6222
 - [x] UI changes https://github.com/wagtail/wagtail/pull/6230
    - [x] Depends on https://github.com/wagtail/wagtail/pull/6234
 - [x] Locale switchers https://github.com/wagtail/wagtail/pull/6460

### For later

 - [x] Logging https://github.com/wagtail/wagtail/pull/6262 https://github.com/wagtail/wagtail/pull/7352
 - [ ] Search changes - No PR yet
 - [ ] Sitemaps changes - No PR yet
 - [x] Support for `copy_for_translation` on any clusterable model
    - [x] Depends on https://github.com/wagtail/wagtail/pull/6277

**Comment by hpoul** [comment]
[Not sure about the right place to ask this question](https://stackoverflow.com/questions/68050653/how-to-make-title-of-images-translatable-in-wagtail) (sorry). But did this RFC consider how things outside the page tree could be translated. Ie. if I have a custom Image class containing "alt" text. Is it really the best solution to duplicate the images to translate alt text and tags? Or is the preferred way to move the "alt" text into the page and consider it part of the page, not the image? (since the RFC mentions something about keeping image and image caption in sync).

**Comment by kaedroho** [comment]
Hi @hpoul, yep, the preferred way is to move the alt text into a field on the page itself, this has the extra benefit of allowing editors to set context-specific alt text as well.

**Comment by thibaudcolas** [comment]
It seems to me most of the above has been implemented so the tracking issue may not be relevant anymore (yay!) For sitemaps, there is #1196. For search, I’m not aware of which issue is most relevant.
