### ISSUE TITLE
UI development documentation upgrade

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8044]
Follow-up to #7978 / #8005. We’ve added the tokens, we need to add their documentation.

## Tasks

- [x] Rework existing docs to be in Markdown, in fewer files
- [x] Generate Storybook documentation page based on Tailwind theme
- [x] Generate link to https://contrast-grid.eightshapes.com/
- [x] Documentation setup for UI components
- [x] Merge or close https://github.com/wagtail/wagtail/pull/5458
- [x] Multilingual support guidelines
- [x] RTL support guidelines

## Testing / review plan

Code review by a member of the UI team.
