### ISSUE TITLE
Tailwind setup follow-up tasks

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8052]
## Tasks

- [ ] Refine integration of Tailwind theme with Sass stylesheets
- [ ] Refine Tailwind setup for logical properties in CSS
- [ ] Set up Tailwind for Windows high contrast mode support

## Testing / review plan

Code review by member of the UI team

**Comment by thibaudcolas** [comment]
PR: https://github.com/wagtail/wagtail/pull/8117
