### ISSUE TITLE
Visual regression test suite prototype

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8138]
Plan: https://docs.google.com/document/d/1SRXjlZ3_f48XGpJrtUaNO80sz_qp_ECAs2p0gFZAO0g/edit?pli=1#heading=h.fugw6yxhc8fc

## Tasks

- [ ] Make prototype on [wagtail-fork](https://github.com/thibaudcolas/wagtail-fork)
- [ ] Review by UI team
- [ ] Run past core team 

## Testing / review plan

UI team review, Scott & Naomi

**Comment by thibaudcolas** [comment]
Prototype: check! https://github.com/thibaudcolas/wagtail-fork/pull/4.

I will keep this issue opened while we gather feedback, but would recommend people comment on https://github.com/thibaudcolas/wagtail-fork/pull/4 directly so it’s all in one place.
