### ISSUE TITLE
Implement page editor’s info side panel

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8145]
Depends on #8136, #8140, #8065. This brand new component will replace information that used to be present in the page’s header, and under the Settings tab. Its implementation needs to match the designs, and replicate logic which might not be there in the designs. [Design link](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-2022?node-id=1895%3A27676)

## Reference screenshot

![info-side-panel](https://user-images.githubusercontent.com/877585/158614770-46c3dde7-876c-467b-b9ed-6247f833f264.png)

## Expected data

Everything as per sub-tasks, as well as:

- Page type
- Page description (#8065)
- Page first publication date

## Tasks

- [x] #8141
- [x] #8142
- [x] #8143
- [x] #8144
- [x] Create a new template
- [x] Add info side panel sections
- [ ] Add Storybook stories as needed
- [x] Implement display logic either in Python or templates as appropriate, based on current implementation
- [x] Add to page editor
- [x] Replace page editor header with new implementation
- [ ] Remove existing components from Settings tab
- [ ] Multilingual support

## Acceptance criteria

- [ ] Matches design 
- [ ] Implementation fully updates existing page editor and removes current component
- [ ] Multilingual support

## Testing / review plan

- [ ] UI testing in German by @stevedya 
- [ ] Mobile testing by @stevedya 
- [ ] Accessibility tests by @thibaudcolas
- [ ] Code review by @thibaudcolas

**Comment by pawan941394** [comment]
sir can i work on this

**Comment by thibaudcolas** [comment]
@pawan941394 no, this is assigned to @stevedya.
