### ISSUE TITLE
Implement new page editor’s History panel

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8146]
This is a follow-up to the Page editor 222 project (#7739), which we aren’t intending to implement at this time, and is ready to pick up based on our designs. Implementation depends on completion of: #8136 and #8140. This will likely be much easier to tackle after #8145 has been implemented as well.

[Design link](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-2022?node-id=378%3A370)

## Reference screenshot

![history-side-panel](https://user-images.githubusercontent.com/877585/158618351-7b8a3500-b1a3-49f5-808c-f4a20963d3fa.png)

## Expected data

- As per current page revisions listing view
- Displaying only the last 20 revisions, with a link to view them all on a separate listing.

## Tasks

- [ ] Create a new template, reusing #8140 
- [ ] Create new component for listing
- [ ] Add Storybook stories as needed
- [ ] Implement display logic either in Python or templates as appropriate, based on current implementation
- [ ] Add to page editor, replacing current "History" link
- [ ] View full history: link tcurrent page revisions listing view
- [ ] Per-row actions: as per page revisions listing view
- [ ] Multilingual support

## Acceptance criteria

- [ ] Matches design 
- [ ] Implementation fully updates existing page editor and removes "History" link
- [ ] Multilingual support

## Testing / review plan

- [ ] UI testing in German by @thibaudcolas
- [ ] Mobile testing by @thibaudcolas
- [ ] Accessibility tests by @thibaudcolas
- [ ] Code review by @thibaudcolas
