### ISSUE TITLE
Implement new Comments side panel styles

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8147]
Implementation depends on completion of: #8136 and #8140. This will likely be much easier to tackle after #8145 has been implemented as well. Potentially worth picking up at the same time #7121.

[Design link](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-2022?node-id=360%3A198)

## Reference screenshot

![comments-side-panel](https://user-images.githubusercontent.com/877585/158621015-37fab6ce-577e-4ad5-b933-f5ff0a09662f.png)

## Expected data

- As per current comments display

## Tasks

- [ ] Include #7121
- [ ] Reuse #8140 
- [ ] Combine with current comments implementation in React
- [ ] Add Storybook stories as needed
- [ ] Multilingual support
- [ ] Components: Avatar, Comment actions, Comment state indicator (footer)
- [ ] To add: Currently can’t resize text field in comment
- [ ] Assuming comment state indicator as-is
- [ ] Assuming comment buttons (Comment / Cancel) as-is
- [ ] CSS outline or box-shadow for focused comment to have it cut through side panel separator (plus negative margin)
- [ ] Accessibility: as-is
- [ ] Customisations to check: none
- [x] ✅ Q: what happens if I save a comment with auto-save, then someone sees it and reply? I won’t see that reply in milestone 1. A: all good since you know someone is updating the page (warning warning)

## Acceptance criteria

- [ ] Matches design 
- [ ] Implementation fully updates existing page editor and removes the current Comments implementation
- [ ] Multilingual support

## Testing / review plan

- [ ] UI testing in German by @thibaudcolas
- [ ] Mobile testing by @thibaudcolas
- [ ] Accessibility tests by @thibaudcolas
- [ ] Code review by @thibaudcolas
