### ISSUE TITLE
Implement Live preview side panel

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8148]
Implementation depends on completion of: #8136 and #8140. This will likely be much easier to tackle after #8145 has been implemented as well.

[Design link](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-2022?node-id=441%3A7329)

## Reference screenshot

![live-preview-panel](https://user-images.githubusercontent.com/877585/158622585-d8435670-992a-4176-a9f0-a32ea789f3eb.png)

## Expected data

- Live preview iframe URL
- Breakpoints from Wagtail settings, including:
  - Icon (for 3-4 defaults set, needs adding to Wagtail) 
  - Label
  - Description?
  - Width
  - Scaling ratio

## Tasks

- [ ] Reuse #8140 
- [ ] Combine with current preview implementation (new route)
- [ ] Implementation: React
- [ ] Add Storybook stories as needed
- [ ] Loading spinner centred when loading saying “Loading preview”
- [ ] Resizer. Resizing whole panel, not just “preview” area
- [ ] Preview rendering updates as you resize (iframe width and scaling)
- [ ] Does the selected breakpoint change as you resize? Q. for whole team
- [ ] Breakpoint buttons:
- [ ] Open in a new tab: same as current preview?
- [ ] Title for iframe
- [ ] Tooltips with text label for buttons
- [ ] Keyboard tabbing: resizer, iframe, buttons

## Acceptance criteria

- [ ] Matches design 
- [ ] Implementation fully updates existing page editor and removes the current preview button

## Testing / review plan

- [ ] UI testing in German by @thibaudcolas
- [ ] Mobile testing by @thibaudcolas
- [ ] Accessibility tests by @thibaudcolas
- [ ] Code review by @thibaudcolas

**Comment by thibaudcolas** [comment]
Implemented in #8671.
