### ISSUE TITLE
Support Draftail editor vertical resizing

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8235]
This will be done outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). This is a bit of an unknown – it could be very straightforward, or a lot of work. According to the designs, fields seem to support both horizontal and vertical resizing. We may want to only support vertical resizing to keep it simple.

### Tasks

- [ ] Investigate simplest options to deliver this (considering either scrolling for small fields, or having minimum height of content height)
- [ ] Add prop to toggle this on/off
- [ ] Add prop to define default size
- [ ] Implement vertical resizing

### Acceptance criteria

- [ ] As an editor, I can vertically resize the editor

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @thibaudcolas
