### ISSUE TITLE
Create rich text links on copy-paste

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8236]
This will be implemented outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). We want Draftail to support creating links in rich text by pasting the URL:

- Pasting a URL onto a text selection will create a link on the text (and override any existing link within the selection). A multi-block text selection creates a link per block.
- Pasting a URL without a text selection (collapsed selection) will create a link with the URL as the text.

This will work for external links (URL detection TBC), mailto link (TBC – `@` sign presence), anchor links (start with `#`), phone links (TBC).

### Tasks

- [x] Check how Wagtail validates link URLs server-side (in and out of rich text) and adjust implementation plan accordingly.
- [x] Implement link detection for desired link types (1 to 4).
- [x] Implement copy-paste processing API to create content on paste (`handlePastedText`)
- [x] Conditionally enable link creation based on link support, and supported link types

### Acceptance criteria

- [ ] As an editor, I can create an external link in rich text by pasting a URL.
- [ ] As an editor, I can turn text into a link in rich text by pasting a URL.
- [ ] As an editor, when I create a link with copy-pasting, the page successfully saves without any validation errors.
- [ ] As a developer, I can constraint which link types are allowed when copy-pasting URLs.

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @thibaudcolas
