### ISSUE TITLE
Implement Rich text / StreamField block picker UI

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8237]
This will be implemented outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). Implementation of the UI for the rich text / StreamField block picker, including block autocomplete widget w/ "Press / to insert" behavior.

- All `blockTypes` items are in the block picker
- `entityTypes` items are in the block picker if they use a `block`
- `controls` items are in the block picker if they use a `type` of `block`

### Tasks

- [ ] New floating UI widget displaying sectioned list of rich text formats / blocks / actions, with full keyboard support
- [ ] "+" button following the current selection’s focus key (collapsed & multiline)
- [ ] "Insert new block /" triggers the appearance of the UI widget (`handleBeforeInput`)
- [ ] Upon selection of a valid option, the `/`-command’s text is removed and the desired action triggers on the given line.

### Acceptance criteria

- [ ] As an editor, I can use my mouse to select a rich text format or block type from within this lateral toolbar
- [ ] As an editor, I can use the keyboard only to select a rich text format or block type from within this lateral toolbar
- [ ] As a developer, I can register rich text formats / block types / arbitrary actions within this toolbar

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @jacobtoppm
