### ISSUE TITLE
Implement floating toolbar for Draftail

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8245]
This will be done outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). Implementation of the new floating toolbar for Draftail, which only shows when text is selected. This toolbar will contain different items than the existing one, with all inline options, and potentially a few predefined block options.

- `inlineStyles` items are in the floating toolbar
- `blockTypes` items of a predefined subset (TBC) show in the floating toolbar
- `entityTypes` items are in the floating toolbar if they use a `decorator`
- `controls` items are in the floating toolbar if they use a `type` of `inline`
- Undo/redo buttons no longer display in this toolbar
- Soft line breaks no longer display in this toolbar

### Tasks

- [ ] Toolbar UI with correct show/hide behavior based on there being a not-collapsed selection
- [ ] Toolbar contains the correct items

### Acceptance criteria

- [ ] As a mouse user, I can apply inline formatting and select other formatting options with the floating toolbar
- [ ] As a keyboard user, I can apply inline formatting and select other formatting options with keyboard shortcuts
- [ ] As a developer, I can control which of my Draftail customisations show in the floating toolbar

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @thibaudcolas

**Comment by thibaudcolas** [comment]
Implemented in Draftail in https://github.com/springload/draftail/commit/22ff9c4f2e87f33d03d6ba2d5894883ccfc8c624. Implementation in Wagtail TODO as part of #8548.
