### ISSUE TITLE
Add character count / max length for Draftail

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8246]
This will be done outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). We want to support basic analysis of the textual contents of Draftail fields:

- Character count (with logic matching the browser’s count for `maxlength`, see [RFC 60](https://github.com/wagtail/rfcs/pull/60)).
- Max length count (same logic as character count, with displayed upper limit).
- Word count (with configurable word splitting and translateable text)
- For backwards compatibility, we will also display `controls` items which have a type of `feedback` ~no `type`~ in the same area of the UI.

### Tasks

- [x] Implement character count logic matching that of browsers’ `maxlength` according to [RFC 60](https://github.com/wagtail/rfcs/pull/60).
- [ ] Create character count UI, with appropriate ARIA attributes for the count (role, aria-describedby).
- [ ] Add `maxLength` prop and UI, with appropriate ARIA attributes, allowing users’ text to overflow the limit to then set `aria-invalid="true"`.
- [ ] Add word count / arbitrary count props and UI, with configurable split logic & translate-able text.
- [ ] Display controls with a `type` of `feedback` (`status` / TBC), ~as well as without `type` in same area with mini toolbar~.

### Acceptance criteria

- [ ] As an editor, I can see the counts increasing as I enter content.
- [ ] As an editor, I know when my content has reached the maximum length, but my text isn’t auto-truncated.
- [ ] As a screen reader user, my screen reader announces the counts and field status as appropriate.
- [ ] As a developer already using `controls`, they work as-is with minimal changes.

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @thibaudcolas

**Comment by lb-** [comment]
For showing the character count in the UI - `output` might be a suitable semantic element that can reference the field via the `for` attribute. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output

**Comment by thibaudcolas** [comment]
Implemented in Draftail in https://github.com/springload/draftail/commit/00a8c0e68c1e64e7f1607ed9ec3bffc13256d9a3. This ended up using the existing `controls` API, so there isn’t much more than an example on the Draftail repository. Implementation within Wagtail will come via #8548.
