### ISSUE TITLE
Spike: Implementation plan to switch all plain-text fields to Draftail

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8247]
This is to plan for the implementation of [RFC 60](https://github.com/wagtail/rfcs/pull/60), looking into how we will deliver the switch to Draftail for all fields, potentially making sure this can be opt-in or opt-out. This will power:

- Inline commenting for plain-text fields (TBC where the comments are stored?)
- Character / word count & max length UX (making sure our implementation is at least as good as a `maxlength`).
- Text analysis (For example https://github.com/takeflight/wagtail-readability or https://github.com/wooorm/write-music)
- Spellchecking / annotations (https://github.com/hinrikur/gc_wagtail, https://github.com/torchbox/npr-poc/blob/master/npr_poc/utils/static/draftail/word-flags.js)

Assignee: @thibaudcolas or @jacobtoppm

### Tasks

- [ ] Create implementation plan from RFC
- [ ] Highlight possible backwards-incompatible changes
- [ ] Create/update corresponding ticket(s)

### Testing & review plan

- [ ] Review implementation plan with @thibaudcolas / @jacobtoppm / @kaedroho

**Comment by lb-** [comment]
As per RFC - https://github.com/wagtail/rfcs/pull/60#issuecomment-1098486070

---

Draft.js has confirmed that it is no longer maintained. The project will no longer receive updates and the GitHub repo will be archived in October of this year (October 2022). 

I think we need to consider this if we are to adopt our wrapper around Draft.js in even more places in Wagtail. This is frustrating I know but I personally do not think we can proceed with this RFC unless we have a more solid underpinning for a large change across basically any text field in Wagtail.

Maybe we can find a different way to solve for comments, feedback, and other features we want to implement around common fields.

https://github.com/facebook/draft-js/issues/3091#issuecomment-1098478193
https://github.com/facebook/draft-js/pull/3136
