### ISSUE TITLE
Single-line Draftail editor

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8248]
This will be done outside of Wagtail, in [springload/draftail](https://github.com/springload/draftail). We want to support an editor only having a single line, so we can use Draftail for plain-text input fields, and rich text that’s inline. WIP: [#7249](https://github.com/wagtail/wagtail/pull/7249).

### Tasks

- [ ] Add a prop to toggle single-line mode on/off
- [ ] Prevent "Enter" creating new blocks in the editor
- [ ] Prevent copy-paste creating new blocks

### Acceptance criteria

- [ ] As an editor, I can copy-paste into the field and multiline text gets copied to a single line

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @thibaudcolas

**Comment by thibaudcolas** [comment]
This has been implemented as of Draftail v2.0 (no stable release yet), merged in #8805. This is undocumented for the time being (needs a final release), but is just a matter of setting `multiline={false}` on the editor.

Demo: https://demo.draftail.org/storybook/?path=/story/docs--single-line

Next step in Wagtail will be #8249.
