### ISSUE TITLE
Single-line RichTextField

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8249]
Implementation of [RFC 46](https://github.com/wagtail/rfcs/pull/46). Depends on #8248. WIP: [#7249](https://github.com/wagtail/wagtail/pull/7249). This is to implement "single-line" rich text server-side, integrating with the relevant Wagtail and Django APIs (DB storage format, rich text diffing, search, translations, etc.)

### Tasks

- [ ] DB field
- [ ] Support in ContentState converters
- [ ] Widget incl. template
- [ ] Widget Telepath adapter
- [ ] StreamField block
- [ ] Comparison support (diffing)
- [ ] Search support
- [ ] Reference count support

### Acceptance criteria

- [ ] As an editor, I can do the same things with a single-line rich text field as I can with multiline

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @jacobtoppm or @kaedroho

**Comment by shayan-oanda** [comment]
Hi all, any progress on this? We'd really appreciate this feature

**Comment by thibaudcolas** [comment]
@shayan-oanda single-line rich text is [on the Wagtail roadmap](https://wagtail.org/roadmap/) in the "Future" area. We’re looking for a feature sponsor for this, to cover the cost of completing the WIP work at #7249.

Alternatively, this can be picked up by any contributor, continuing from #7249.

**Comment by thibaudcolas** [comment]
2025 update: I’ve spent some time reviewing our plans for this, Draftail support for single-line fields has shipped and seems to work well, so now we’re missing the integrations with all of Wagtail’s features (search, diff, references, comments, etc). This is still available for sponsorship or contributions if anyone wants to see it through.

**Comment by thibaudcolas** [comment]
Revisiting this - with LLMs, I think this now much more approachable if anyone wants to give this a go. I went pretty far with my [draft PR from 2023](https://github.com/wagtail/wagtail/pull/7249)
