### ISSUE TITLE
Generic chooser views

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#8480]
Introduce a `wagtail.admin.views.generic.chooser` module to serve as a common base implementation for chooser modals. This can be loosely based on [wagtail-generic-chooser](https://github.com/wagtail/wagtail-generic-chooser) but should incorporate improvements as outlined in https://github.com/wagtail/wagtail-generic-chooser/issues/44: in particular, using the table UI component for listing views, and using 'partial' HTML fragments for the browser results view and 'create' form submission so that we aren't re-rendering the whole modal.

Acceptance criteria:

- [x] A documented base set of views exists in `wagtail.admin.views.generic.chooser` (#8662)
- [x] A documented viewset exists in `wagtail.admin.viewsets.chooser` (#8662)
- [x] A base chooser widget implementation is provided and documented (#8662)
- [x] A base StreamField chooser block is provided and documented (#8820)
- [ ] The page chooser mechanism inherits from this base implementation
- [x] The image chooser mechanism inherits from this base implementation (#8778, #8804)
- [x] The snippet chooser mechanism inherits from this base implementation (#8711, #8717)
- [x] The document chooser mechanism inherits from this base implementation (#8776, #8777)
- [x] A basic chooser for an arbitrary model can be implemented with minimal new code - simply extending the base viewset/widget class and specifying the model as an attribute (#8662)
- [x] New instances can be created through the chooser view (#8726)
- [x] The listing view uses the `wagtail.admin.ui.tables` component (#8662)
- [x] Listings are searchable (where the model provides this) (#8669)
- [ ] Listings are filterable via `django-filters` filters
- [x] Data sources other than models (e.g. django-rest-framework API endpoints) can be used (#8855)
- [ ] Where custom logic is common to chooser modals and widgets (e.g. converting an object ID to a dict representation that can be used for widget rendering), code is shared between them

**Comment by phildexter** [comment]
1. We can choose basic Snippets using the new chooser (from the chooser widget or a streamfield block).
2. We can create a new Snippet through the new chooser (from the chooser widget or a streamfield block).
3. We can search for a Snippet through the new chooser (from the chooser widget or a streamfield block).
4. We can filter objects through the new chooser.
5. We can do 1-4 for documents.
6. We can do 1-4 for images.
7. We can do 1, 3 and 4 for pages.
8. We can do 1-4 for sources other than models stored within the Wagtail DB
9. Documentation on how to extend

**Comment by lb-** [comment]
Once done, is the plan to deprecate https://github.com/wagtail/wagtail-generic-chooser/ ?
If so - will we re-assess & move those open issues to this repo (if still applicable)?

**Comment by gasman** [comment]
@lb- Yep, the plan is to deprecate wagtail-generic-chooser - so yes, reviewing those open issues is a good plan. From a quick scan through the list, there's a mix of things I hope to address in the rewrite (better filtering via django-filters, cleaner API for DRF data sources) and more general wishlist items that are probably a better fit for the Wagtail project anyhow (multiple selection, generalised link choosing).

**Comment by lb-** [comment]
@gasman  just adding two items of feedback from other PRs

1. [ ] Search button showing in an edge case where it should not (non-indexable but translatable model) - see https://github.com/wagtail/wagtail/pull/8717#issuecomment-1169497578
2. [ ] Layout review probably needed, content appears a bit close to the purple header in chooser modals - see https://github.com/wagtail/wagtail/pull/8711#pullrequestreview-1022696894
3. [ ] We are using `h2` with `role='alert'` for some chooser search results, other times we use `p` with the role - I opted to not raise a new bug for this as maybe that will be covered by this issue, if not let me know and I can split out to a new bug. https://github.com/wagtail/wagtail/pull/8669#discussion_r907913644

**Comment by gasman** [comment]
Thanks @lb-!
I've removed the search button in my latest PR (to be opened shortly) - the document chooser doesn't have it, and it's unnecessary because all of the inputs auto-submit on change anyway. Given that the design is sub-par (not aligned with the other fields and taking up a load of vertical space) I suspect it's not meant to be there, and it was deliberately removed from the others at some point (but the snippet chooser was overlooked because none of the snippets on the stock bakerydemo site are searchable or translatable).

**Comment by gasman** [comment]
I think this can be considered done now. Out of the remaining bullet points:

* The page chooser mechanism inherits from this base implementation - the page chooser is custom enough (tree navigation, integration with the general link builder) that there's little benefit to doing this
* Listings are filterable via django-filters filters - this is a nice-to-have, and django-filters is definitely the path we'd like to go down if there is a need for adding filters on a per-model basis (both here, and in wagtail.admin.views.generic.models.IndexView) - but for now we can get by with the filters that are "baked in" to the generic view (search, collections, locales). Defer this until there's a clear use-case for it.
* Where custom logic is common to chooser modals and widgets (e.g. converting an object ID to a dict representation that can be used for widget rendering), code is shared between them - opened as a new issue #9289
