### ISSUE TITLE
Integrate Draftail improvements with Wagtail

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8548]
This is to track Draftail updates, to make use of improvements implemented outside Wagtail.

### Tasks

- [x] Implement character count / max length for Draftail: use new `maxLength` and character count props (#8246)
- [x] Create rich text links on copy-paste: provide supported link types to Draftail (#8236)
- [x] Implement floating toolbar for Draftail: update `controls` to have a `type` (#8245)
- [x] Implement Rich text / StreamField block picker UI: integrate new API (#8237)

### Acceptance criteria

N/A

### Testing & review plan

- [ ] Cross-browser testing @thibaudcolas
- [ ] Code review @jacobtoppm
