### ISSUE TITLE
UX Unification - adopt breadcrumbs across all of Wagtail

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8645]
| Part of [UX Unification - header component with variations #8539](https://github.com/wagtail/wagtail/issues/8539) |
| --- |

## Is your proposal related to a problem?

- Currently there are at least **four** different variants of breadcrumbs in Wagtail, with three distinct styles used across these variants.
- This creates a problem where the design across Wagtail does not feel unified and also can cause confusion for new editors.

## Describe the solution you'd like

- Progressively adopt the new breadcrumbs (aka breadcrumbs next) across all parts of Wagtail.

### 1 - Existing JS to work in any location

* [X] [Breadcrumbs next rely on data-slim-header to be present in DOM #8644](https://github.com/wagtail/wagtail/issues/8644)
   * Ensure that the new breadcrumbs JS can work even when the breadcrumbs are not present inside the new `data-slim-header`, see above issue for full details.

### 2 - page listing index

- [x] Adopt new breadcrumbs in page listing index (keep the light grey background which will sit above the current teal header)
- try `{% explorer_breadcrumb parent_page use_next_template=True %}` in wagtail/admin/templates/wagtailadmin/pages/index.html
- Fix the odd grey colour that is being added
- Test a bunch of scenarios including root page, deeply nested
- test add a test `wagtail/admin/tests/pages/test_explorer_view.py` that checks the `data-breadcrumb-next` is used & the correct template is used
- Test out manually keyboard interaction works ok

![Image](https://user-images.githubusercontent.com/1396140/172556306-b34d7096-dbe2-4aa9-9c47-75b72aea468b.png)

### 3 - page chooser

- [x] Adopt new breadcrumbs in page chooser listing results
  - does not get added inside a header, should be expanded at all times  `is_collapsible`
  - JS  behaviour will not be needed for this variant so we want to make sure it works well `wagtail/admin/templates/wagtailadmin/shared/chooser_breadcrumb.html`
- locale picker needs to be moved out of the breadcrumbs into the element above
- need to ensure that the URLs are the same (`admin/choose-page/123/?blah`)
- need to solve the issue of the root page showing the URL correctly if needed
- ensure that the page selected is not shown, only its parents and all the way back to root `include_self=False`?
- look at styling (as per chooser demo screenshots below) but all good if this comes a bit later
- usage to validate
  - page chooser link (e.g. bakerydemo home page edit)
  - page chooser via block
  - page chooser via rich text editor
  - deeply nested page (e.g picking home page)
  - shallow nested page

### 3a - Add a non-collapsible version of breadcrumbs

* [x] Add ability for breadcrumbs to be non-collapsible & expanded (aka `is_collapsible`)
* Currently the behaviour is to be collapsed on load and you click to expand, this may not be suitable for some locations.
* There should be a way to pass in `is_collapsible=True` to  `explorer_breadcrumb` where the default will be false.
* When true the collapse/expand button will be rendered
* When true the `data-breadcrumb` attribute will be used
* It should add a class (which will make more sense when the CSS is being done) for the modified variant
* `explorer_breadcrumb` should be the only tag for now that needs this update
* Add a static variant to storybook
* [`wagtail/admin/templatetags/wagtailadmin_tags.py`](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templatetags/wagtailadmin_tags.py#L60)
* Add test that the right variant of the breadcrumbs is used `wagtail/admin/tests/pages/test_create_page.py`
```
TestPageCreation
    # .... other tests
    def test_create_page_breadcrumbs(self):
        response = self.client.get(
            reverse("wagtailadmin_pages:add_subpage", args=(self.root_page.id,))
        )
        self.assertEqual(response.status_code, 200)

        # test that the breadcrumb template was used
        # check that the rendered output contains `data-breadcrumb-next`
```

![Image](https://user-images.githubusercontent.com/1396140/172556368-ba35c8d0-bee8-4e97-99d6-28959713766c.png)

### 4 - use new breadcrumbs in the move page
- [x] Check adoption of new breadcrumbs in **move** page
- **UPDATE** - breadcrumbs on move pager are no longer needed due to https://github.com/wagtail/wagtail/pull/8689
  - instead we will just clean up the legacy breadcrumbs template's & template tag
- wagtail/admin/templates/wagtailadmin/pages/move_choose_destination.html
- uses the different breadcrumb template `wagtail/admin/templates/wagtailadmin/shared/move_breadcrumb.html`
- See `move_breadcrumb` in wagtail/admin/templatetags/wagtailadmin_tags.py
- Write a test in each usage test file that `data-breadcrumb-next` is rendered & the relevant breadcrumbs template gets used

<img width="1592" alt="Screen Shot 2022-06-13 at 3 41 04 pm" src="https://user-images.githubusercontent.com/1396140/173287407-46b9a7fb-9104-4413-823c-c079995b7343.png">

### 5 - modeladmin page management

- [x] Adopt new breadcrumbs in modeladmin pages (add/edit) - should be done under [modeladmin: Breadcrumbs visual bugs #6904](https://github.com/wagtail/wagtail/issues/6904)
- Reminder - to reproduce these you need to have a page type / pages editable in modeladmin (bakerydemo does not have this set up out of the box) AND use `inspect_view_enabled=True`

__adding to bakerydemo__
```python
# bakerydemo/base/wagtail_hooks.py
from bakerydemo.blog.models import BlogPage

# ...

class BlogPageAdmin(ModelAdmin):
    inspect_view_enabled = True
    model = BlogPage

# ...
modeladmin_register(BlogPageAdmin)
```

**Updated actions**

- remove the modeladmin breadcrumbs completely (from both the inspect view and choose_parent views)
- to provide a way to go 'back' to the listing, copy/paste the same link that exists in the inspect view
- `<p class="back"><a href="{{ view.index_url }}" class="icon icon-arrow-left">{% blocktrans trimmed with view.verbose_name as model_name %}Back to {{ model_name }} list{% endblocktrans %}</a></p>`
- We will look at this general problem in the buttons work or maybe the header work
- Once done - should be able to close the #6904 as solved a different way (although it actually works fine now, but we don't want to put screenshots until the breadcrumbs are removed)

![Image](https://user-images.githubusercontent.com/1396140/172556200-cb7b385d-6130-4d81-8af1-453db7dd7288.png)

### 6 **(DE-SCOPED)** - CSS to work in any location

* **Update** Due to time constraints and this not adding much value right now we will leave the classes as is
* Adopt latest convention for CSS in the new Breadcrumbs
* This may make sense further up in the ordering
* move to BEM classes `w-breadcrumb` etc
* remove background colour on breadcrumbs so that they can appear on any background `w-bg-grey-50`
* Add a CSS file and move all styles from Tailwind utility classes to the css file - these can be added to `client/scss/components/_breadcrumb.scss` for now as we will eventually just remove the existing `.breadcrumb` class and keep the same file
* Remember to pull out the utility classes from the JS also
* We should be able to remove the `{% with breadcrumb_link_classes...` section and nest the whole breadcrumbs back in

#### Phase 2 - clean up

- [x] Misc clean up notes so we do not forget 
- 👍 see if we can, or have time to, refactor `move_breadcrumb` into `explorer_breadcrumb` so there is only one template tag called `breadcrumbs` (plural)
- 👍 `use_next_template` should not be needed anywhere
- 👍 Remove any HTML templates that are now unused, remove non-next storybook, ensure there is no `next` there is just breadcrumbs
- Remove any CSS for the legacy `.breadcrumb`
- 👍 Remove storybook for the legacy breadcrumb
- 👍 Update all references to breadcrumb next (pattern library) to just be breadcrumb
- 👍 If not already done, delete the modeladmin breadcrumb template
- 👍 js is called `breadcrumbs` and html is called `breadcrumb` (would be good to have one name)
- 👍 `breadcrumb-next.html` should be renamed to `breadcrumb_next.html` (or maybe this file will not exist)
- 👍 see if we should remove `wagtail/admin/templates/wagtailadmin/shared/chooser_breadcrumb.html` and pull the content up to the parent template 
- 👎 **(not required)** rename the breadcrumbs JS file to match preferred convention
- 👎 **Still needed by other code** remove `.page-results a.navigate-pages, `

#### De-scoped - Add new usage

- [ ] add any new issues for future enhancements or clean up items

This likely will not happen as breadcrumbs should probably only be used for page path like things, we can review whether something else may be suitable like a back button.

We will need to chat as a team and work out what should happen with the following issues, either close them as not going to implement or think of an alternative way to provide just a 'parent'/'back' breadcrumb (that is not a breadcrumb).

Maybe these can be solved with something in the header?

- [ ] [Snippets - Add breadcrumb menu to snippet pages #8597](https://github.com/wagtail/wagtail/issues/8597)
- [ ] #8767
- [ ] potentially a new type of breadcrumb for 'single use' back to listing type thing (snippets, modeladmin etc) and gives us something to put in the slim header

### Additional context

- This is part of a wider effort to clean up the header usage  [UX Unification - header component with variations #8539](https://github.com/wagtail/wagtail/issues/8539)

**Comment by lb-** [comment]
@thibaudcolas  please review this issue, I think it is best to adopt the new breadcrumbs in isolation of the header, most cases currently have the breadcrumbs sit above the header content so this will be a great first step. Also there is a case (page chooser) where we have breadcrumbs that are not part of a page header.

Can you please advise
- adding a `is_compact` to show the breadcrumbs in collapsed state on load to the `explorer_breadcrumb` template tag - default will be false.
- In each scenario above, what should be collapsed by default (my guess is none for now)
- Are there other breadcrumbs we have missed.

My goal here is to think about if we did this & only this for 4.0 - we would preserve an almost 1:1 interaction but just the new designs.

@PaarthAgarwal  please also review and let me know what you think, we will split things out to their own issues as needed, some issues already exist.

**Comment by thibaudcolas** [comment]
I can see two design decision points that have to be resolved here:

- Is it appropriate for breadcrumbs to be used to navigate between the hierarchy of views in the CMS. Right now our breadcrumbs are only used to navigate within the hierarchy of the _site’s pages_. Technically ModelAdmin already does this in its inspect view ([see example screenshot](https://github.com/wagtail/wagtail/issues/8539#user-content-modeladmin-inspect)), but this doesn’t feel like a decision we clearly made.
- For the breadcrumb in choosers, is it really appropriate for it to have the same appearance as the slim header’s breadcrumb.

There is also the question of how much the current "slim breadcrumb" should be adapted for usage outside of the page editor.

**Comment by lb-** [comment]
@thibaudcolas 

My thoughts - aside from the Snippets idea - all breadcrumbs usage is only related to page hierarchy. 

Page listing. What if we kept the light grey BG. It's contrasted against the real header but it would be above it so maybe not a huge compromise to get momentum on this work.

As for page chooser - I think we should aim for the component / classes and even template tag to be all the same but maybe a different variant styling wise. Unless you are seeing the breadcrumbs as being removed entirely from the page chooser. 

Let me know what you think for that response and I can try to rework this issue with some clear starting points for Monday (when we start GSoC in earnest).

**Comment by thibaudcolas** [comment]
All sounds good to me!

Here are the [WIP designs for the page chooser](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=5404%3A48899):

![page-chooser-wip](https://user-images.githubusercontent.com/877585/172660868-2a46b6b4-1821-40db-ad3b-0a3d7e91c8ec.png)

If we want to tackle this I would focus on retrofitting the breadcrumb style in the third example. Note in our current implementation there is also a locale selector in this area, which isn’t reflected in the designs but does need to remain.

**Comment by lb-** [comment]
updated based on feedback

**Comment by lb-** [comment]
Paarth to have a read of

* https://docs.djangoproject.com/en/4.0/howto/custom-template-tags/ - how custom template tags work
* Read through this file `wagtail/admin/templatetags/wagtailadmin_tags.py` specifically `explorer_breadcrumb` & `move_breadcrumb`
* Have a read through the next breadcrumbs HTML template `wagtail/admin/templates/wagtailadmin/shared/breadcrumb-next.html` and think about BEM classes structure

**Comment by PaarthAgarwal** [comment]
>remove background colour on breadcrumbs (appearing when in storybook, not sure why)

It's because of this class `w-bg-grey-50`.

**Comment by lb-** [comment]
Update - did a bunch of re-org of this with Paarth on a call today - focusing on the smaller things first and moving the CSS refactor until later as it may be a bit large.

**Comment by lb-** [comment]
@thibaudcolas  after walking though the breadcrumbs that are used in modeladmin - they are really just another instance of this 'I want to go back to the previous listing in the admin' scenarios and not actual breadcrumbs for a page tree.

We discussed today and will simply remove these model admin breadcrumbs.

<img width="1340" alt="Screen Shot 2022-06-24 at 4 25 34 pm" src="https://user-images.githubusercontent.com/1396140/175475959-44ab0350-e735-499e-9861-3cba9f25711e.png">

**Comment by lb-** [comment]
Simple breadcrumbs work has been split to https://github.com/wagtail/wagtail/issues/8767
