### ISSUE TITLE
Header design review feedback

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9034]
Small fixes to the headers’ styles, though this component can be tricky to work with so they might prove hard to implement.

## Dashboard avatar header

- [x] Dashboard avatar header position, alignment, font styles (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9551%3A47788&t=9R2rCziRg0ANh9Df-4)) (#9188)
- [x] Dashboard summary icons sizes & alignment (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9551%3A47788&t=9R2rCziRg0ANh9Df-4)) (#9188)

## Slim header

- [x] Shift breadcrumb across so that the title of the breadcrumb aligns with the C of the content tab (#9090)
- [x] Snippet listing alignment of breadcrumb, title and checkboxes (#9090)
- [x] Breadcrumb collapse icon size for listing variant of slim header (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9551%3A47789&t=9R2rCziRg0ANh9Df-4))
- [x] Right-side spacing for listing variant (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9551%3A47789&t=9R2rCziRg0ANh9Df-4))
- [x] Size of "More" button / icon in editor variant (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9551%3A47790&t=9R2rCziRg0ANh9Df-4))

## Generic header

- [x] User edit screen - heading space above should be bigger and below should be smaller, so it’s more uniform
- [x] Spacing above and below the header (see [Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9578%3A57712&t=zxYy9ZM5omAblLZd-4))

**Comment by lb-** [comment]
@PaarthAgarwal please have a read of this - the issue list of a bit vague but we might try to help @stevedya out with some fixes.

**Comment by lb-** [comment]
@stevedya  - if it is ok we may pass this one back to you, I spoke with Paarth tonight and to be honest we are not 100% sure how to action this well.

Also - not sure if these issues are critical blockers for 4.0 either.

Will let you make the call and if you get a PR up I will be happy to review it.

Let us know if we can help with this in the scope of GSoC.

**Comment by stevedya** [comment]
@lb- Sure! No problem at all i'm happy to take a look at this one after some of the release blocker issues are completed 🙂
