### ISSUE TITLE
Add button to collapse all sections of the page at once

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9152]
As of Wagtail 4.0, all panels / StreamField blocks / InlinePanel child items are collapsible, all using the same "panel" component. The next step is to add a "collapse all" button, which collapses all of those panels at once.

View the [proposed designs in Figma](https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=4445%3A27987). Screenshot:

![Image](https://user-images.githubusercontent.com/877585/188685182-02a6cdae-cbde-4407-b937-b2c006a083df.png)

## Open questions

- [ ] The designs were made with the [page editor minimap](https://github.com/wagtail/wagtail/issues/8673) in mind. TBC where we place the button since the minimap hasn’t been implemented yet
- [ ] TBC which views exactly we add this to – pages, snippets, etc.
- [ ] Upon activation, does the button turn into "Expand all"?
- [ ] Is the wording in the designs confirmed? Technically some of those collapsible sections aren’t fields – "Collapse all sections"? "Collapse all panels"?

## Implementation plan

Here is the existing [`toggleCollapsiblePanel`](https://github.com/wagtail/wagtail/blob/main/client/src/includes/panels.ts#L5) logic. The panels and their respective toggles should be updated in the same way with the "collapse all" feature.

For starters, we would most likely add this to pages [create.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/pages/create.html) and [edit.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/pages/edit.html) views.

- Initialising of the button should either be done in `initCollapsiblePanels`, or in a separate function called similarly
- Button styles for reference: https://github.com/wagtail/wagtail/blob/aa70a9f5bd47610fb199b1bb7cf5e0ad5d39c9bc/wagtail/admin/templates/wagtailadmin/widgets/chooser.html#L39

## Test plan

- [ ] Check what happens with events firing multiple times as all sections collapse (`commentAnchorVisibilityChange`)

**Comment by helenb** [comment]
Further questions / issues to resolve:

- Is it correct that the aria-controls for the expand / collapse all button should list the ids of all the panels (div element with class `w-panel__content`)? If so, I may need some advice on getting these ids from the parent template (`edit.html`). Potentially they could be added with JavaScript if it is hard to add them in the template.
- When we collapse all, should any fields containing errors remain open?
- For now, the collapse all / open all is calling the `toggleCollapsiblePanel` function for each toggle - this means that the events this function fires are sent multiple times - to check if this is an issue for comments
- Should we fire another custom event to say that all panels have been collapsed / expanded

**Comment by helenb** [comment]
Draft MR to show work in progress: https://github.com/wagtail/wagtail/pull/9167

**Comment by helenb** [comment]
@thibaudcolas I think it is all behaving as expected with comments, but would appreciate you testing that as I'm less familiar with the expected bevaviour.
