### ISSUE TITLE
Login screen design improvements

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9715]
Figma link: https://www.figma.com/file/h67EsVXdWsfu38WGGxWfpi/Wagtail-Design-System?node-id=9578%3A57713&t=zxYy9ZM5omAblLZd-4

## TODO

- [ ] Switch to the full Wagtail logotype, with updated bird (thicker feathers white stroke)
- [ ] Remove "*" asterisk indicators next to field labels

## TBC

- [ ] Move "Forgotten password?" to be off to the right of the "Remember me" checkbox
- [ ] Change forgot password label to "Forgot your password?"

**Comment by lb-** [comment]
I cannot seem to access that Figma (might not be public), nonetheless, here are some comments from previous work done via https://github.com/wagtail/wagtail/issues/2309 & others (links below).

Not huge blockers - more just notes from what we learned.

### Considerations

* Wagtail Logo on login page - need to consider windows high contrast mode both dark & light variants
* Asterisk indicators - I guess that makes sense on a log in page but I know there has been a bit of push back on other fields (page title) where that was removed, but login fields may be different so all good.
* Forgotten password position - Paarth & I did try this but we ran into issues when also trying to preserve both accessibility (tab order) and the existing documented template override capacity https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/login.html#L48
  * See that the remember me is outside the block `extra_fields` but within the block `fields`
  * Additionally, the remember me checkbox may need to be conditional in the future
* Borders - If changing borders, be sure to consider what happens if `above_login` and/or `below_login` blocks are customised.

### Links

* https://github.com/wagtail/wagtail/pull/8951
* https://github.com/wagtail/wagtail/pull/8951
* https://github.com/wagtail/wagtail/issues/9350
* https://github.com/wagtail/wagtail/issues/2309

**Comment by salty-ivy** [comment]
Figma link in accessible

**Comment by syedimtiyazali20** [comment]
Please Assign me this issue. I will definitely do it for you.

**Comment by syedimtiyazali20** [comment]
By the way, Figma link is not accessible (error = Hmm, we couldn't find that one) is statement is showing there.

**Comment by lb-** [comment]
@SyedImtiyaz-1 - please note that there are two previous comments that advise the figma link is not working. 

Also this issue is flagged as needs design decision so I do not think it's really ready for anyone to pick up. 

We also Only really assign issues to the core team. Hopefully you can find a suitable good first issue that has not been worked on or has not had any traction in some time.

**Comment by SyedImtiyaz-1** [comment]
Sure, I'll find.
